name = "PauliStrings"
uuid = "f07625cc-80e4-4099-a362-36a3484d9bcc"
authors = ["Nicolas Loizeau <nicolas.loizeau@nbi.ku.dk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
